### ISSUE TITLE
Now Playing: (video title)

### ISSUE THREAD

**Issue by ShrewdLou** [boucaud/youtube-shuffle#1]
Your shuffle tool is excellent! Just donated a coffee as "Aaron K" or cursafig@...

My request is probably simple to code.
Above the video, where it reads "Now Playing", it would be helpful if it read "Now Playing: (video title)"

Because, after 10 or so videos have played, the highlighted currently playing video is below the displayed contents, and I have to walk over to my mouse to scroll down to see what's playing.

Adding this feature would show the current video title "at a glance".

Thank you!

**Comment by boucaud** [comment]
Hello @ShrewdLou !

First of all, thank you for your feedback and support !

I have implemented this feature (you were right that it was simple to do).

It should be deployed in the evening.

Thanks again !

**Comment by ShrewdLou** [comment]
Thank you! It works perfectly now!
