### ISSUE TITLE
Playlists don't update

### ISSUE THREAD

**Issue by The-Phantom-Cat** [boucaud/youtube-shuffle#2]
Once you enter a playlist here, if you update it on youtube and then re-enter it, it won't add the new videos here.

**Comment by boucaud** [comment]
Hi, playlists are cached on a weekly basis to avoid unnecessary calls to the Youtube API. That means you should see your playlist update after a few days.

I'm afraid I don't have the time right now to implement a better system. Contributions are of course welcome.
