### ISSUE TITLE
Watch on Youtube button breaks functionality

### ISSUE THREAD

**Issue by Hazard15301** [boucaud/youtube-shuffle#5]
The shuffle feature seems to have been broken as of recently. Usually I can get the first video in a playlist to play, but after that, all the videos have to "Watch on Youtube" button in the lower left corner and will refuse to play.

**Comment by boucaud** [comment]
This should be fixed now. Can you test on your end ?

**Comment by Hazard15301** [comment]
Fixed! Working perfectly again, thank you!
